[package]
name = "tachyon_common"
version = "0.1.0"
edition = "2021"
authors = ["Tachyon Team"]
license = "MIT OR Apache-2.0"

[dependencies]
serde.workspace = true
tracing.workspace = true
zeroize.workspace = true
once_cell.workspace = true
reqwest.workspace = true

[features]
default = []

